apiVersion: v1
kind: Pod
metadata:
  labels:
    run: capabilitie
  name: sec
spec:
  containers:
  - image: busybox
    name: cap
    securityContext:
     capabilities:
      add: ["NET_ADMIN", "SYS_TIME"]
    command: ["bin/sh", -c, "sleep 3600"]
