apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: cfg-volume
  name: nginx
spec:
  volumes:
  - name: nginx-volume
    configMap:
     name: cfgvolume
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: nginx-volume
      mountPath: /etc/cfg
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
