apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: config-env-pod
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - configMapRef:
       name: env-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
