apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
    - name: KEY1
      valueFrom:
       configMapKeyRef:
        name: comfig1
        key: key1
    - name: KEY22
      valueFrom:
       configMapKeyRef:
        name: comfig1
        key: key2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
