apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
   app: nginx-pv
  name: nginx
spec:
  volumes:
  - name: mynginxvol
    persistentVolumeClaim:
     claimName: task-pvc-volume
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: mynginxvol
      mountPath: /usr/share/nginx/html
    
