apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: livenesspod
  name: nginxreadiness
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    readinessProbe:
     httpGet:
      path: /
      port: 80
   
