apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: probes
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    readinessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 20
     periodSeconds: 25
    livenessProbe:
     httpGet:
      path: /healthz
      port: 80
     initialDelaySeconds: 20
     periodSeconds: 25
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
