apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
   app: redis-vol
  name: redis
spec:
  volumes:
  - name: podvol
    emptyDir: {}
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - name: podvol
      mountPath: /tmp/redis 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
