apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: sa-pod
  name: sapod
spec:
  serviceAccountName: admin
  containers:
  - image: busybox
    name: busybox
    command: ["bin/sh", "-c", "sleep 3600"]
