apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secbusybox
  name: secbusybox
spec:
  securityContext:
   runAsUser: 1000
   runAsGroup: 2000
  containers:
  - args:
    - bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: secbusybox
    securityContext:
     runAsUser: 99
     runAsGroup: 100
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
