apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: secrets
  name: secret-pod
spec:
  containers:
  - image: nginx
    name: secret-pod
    envFrom:
    - secretRef:
       name: mysecret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
