apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sidecar
  name: sidecar
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /var/log
      name: logs
    command: ["/bin/sh", "-c", "while true; do echo hi iam from main container >>/var/log/index.html ; sleep 5; done"]
  - image: nginx
    name: sidecar
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: logs
