apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: [bin/sh, -c, "echo i am from busy pod; sleep 3600;"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
