apiVersion: v1
kind: Pod
metadata:
  labels:
   app: config-from-another
  name: anotherone-pod
spec:
  containers:
  - image: nginx
    name: anotherone-pod
    envFrom:
    - configMapRef:
       name: anotherone
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
