apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
   app : config-pod
  name: option-pod
spec:
  containers:
  -  image: nginx
     name: pod
     env:
     - name: option
       valueFrom:
        configMapKeyRef:
         name: options
         key: var5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
