apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-secret-pod
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    env:
    - name: USERNAME
      valueFrom:
       secretKeyRef:
        name: mysecret2
        key: username
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
