apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
   app: config-load-as-vol
  name: nginx-vol-pod
spec:
  securityContext:
   runAsUser: sohit
  volumes:
  - name: myvolume
    configMap:
     name: cmvolume   
  containers:
  - image: nginx
    name: nginx-vol-pod
    volumeMounts:
    - name: myvolume
      mountPath: /etc/lala 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
