apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-secret-pod
  name: nginx-secret
spec:
  volumes:
  - name: secret-volume
    secret:
     secretName: mysecret2
  containers:
  - image: nginx
    name: nginx-secret
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
