apiVersion: v1
kind: Pod
metadata:
 name: multi-container
 labels:
  app: multi-container-pod
spec:
 containers:
 - name: redis
   image: redis:latest
   imagePullPolicy: IfNotPresent
   ports:
   - containerPort: 6379
   resources:
    limits:
     memory: "128Mi"
     cpu: "100m"
    requests:
     memory: "128Mi"
     cpu: "100m"
 - name: server
   image: lrakai/microservices:server-v1
   ports:
   - containerPort: 8080
   resources:
    limits:
     memory: "128Mi"
     cpu: "100m"
    requests:
     memory: "128Mi"
     cpu: "100m"

   env:
   - name: REDIS_URL
     value: redis://localhost:6379
 - name: counter
   image: lrakai/microservices:counter-v1
   resources:
    limits:
     memory: "128Mi"
     cpu: "100m"
    requests:
     memory: "128Mi"
     cpu: "100m"

   env:
   - name: API_URL
     value: http://localhost:8080
 - name: poller
   image: lrakai/microservices:poller-v1
   resources:
    limits:
     memory: "128Mi"
     cpu: "100m"
    requests:
     memory: "128Mi"
     cpu: "100m"

   env:
   - name: API_URL
     value: http://localhost:8080
   
 

  
