apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sidecarpattern
  name: sidecar
spec:
  volumes:
  - name: outputs
    emptyDir: {}
  containers:
  - image: nginx
    name: sidecar
    command: ["bin/sh", "-c", " a=1;while true;a=`expr $a + 1`;do echo $a >> /output/log.txt;sleep 30;done;"] 
    volumeMounts:
    - name: outputs
      mountPath: /output/
  - image: debian
    name: log
    command: ["bin/sh", "-c", "sleep 90; while true; do echo | cat /output/log.txt; sleep 30; done;"] 
    volumeMounts:
    - name: outputs
      mountPath: /output/

