apiVersion: v1
kind: Pod
metadata:
 name: web-server
 labels:
  app: web-server
  location: india
spec:
 containers:
 - image: nginx:latest
   name: web-server
   ports:
   - containerPort: 80
   resources:
    limits:
     cpu: "500m" # 500 m = 500 mili cpu ->1/2 cpu
     memory: "128Mi"
    requests:
     cpu: "500m" # 500m =500 millicpue = 1/2 cpu
     memory: "128Mi" # 128 mebibytes -> more than 128MB 
 - image: nginx:latest
   name: client
   command: ["bin/sh", "-c", "sleep 30;echo $(date); curl localhost:80;"]
   resources:
    limits:
     cpu: "500m" # 500 m = 500 mili cpu ->1/2 cpu
     memory: "128Mi"
    requests:
     cpu: "500m" # 500m =500 millicpue = 1/2 cpu
     memory: "128Mi" # 128 mebibytes -> more than 128MB 
