apiVersion: v1
kind: Service
metadata:
 labels:
  app: counter-poller
  tier: data
 name: backend
spec:
 ports:
 - name: redis
   port: 6379
   protocol: TCP
 type: ClusterIP
 selector:
  tier: data
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: counter-poller
    tier: data
  name: backend
spec:
  containers:
  - image: redis:latest
    name: backend
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
    
