apiVersion: v1
kind: Pod
metadata:
  labels:
    app: counter-poller
    tier: frontend
  name: client
spec:
  containers:
  - image: lrakai/microservices:poller-v1
    name: poller
    env:
    - name: API_URL
      # DNS WAY TO GET SERVICE DISCOVERY -> ip-> servicename: namespace:port{port needs to extracted from SRV DNS record}
      value: http://$(SERVER_SERVICE_HOST):$(SERVER_SERVICE_PORT_WEBSERVER)
  - image: lrakai/microservices:counter-v1
    name: counter
    env:
    - name: API_URL
       # DNS WAY TO GET SERVICE DISCOVERY -> ip-> servicename: namespace:port{port needs to extracted from SRV DNS record}
      value: http://server:8080

