apiVersion: v1
kind: Service
metadata: 
 name: service-layer
 labels:
  app: multi-pods
spec:
 ports:
 - port: 8080
 selector:
  layer: service-layerpod
---
apiVersion: v1
kind: Pod
metadata:
 name: service-layer
 labels:
  app: multi-pods
  layer: service-layerpod
spec:
 containers: 
 - name: servicelayer
   image: lrakai/microservices:server-v1
   ports:
   - containerPort: 8080
   env:
   - name: REDIS_URL
     value: redis://$(DATA_TIER_SERVICE_HOST):$(DATA_TIER_SERVICE_PORT_REDIS)                                             
     # value: redis://localhost:6379
