apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busy
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - env
    image: busybox
    name: busy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
