apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: multipod
  name: nginx
spec:
  volumes:
   - name: data
     emptyDir: {}
  initContainers:
  - args: #
    - /bin/sh #
    - -c #
    - wget -O /work-dir/index.html http://kubernetes.io #
    image: busybox #
    name: box #
    volumeMounts:
    - name: data
      mountPath: /work-dir  
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
