apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
       cpu: "1"
       memory: 256Mi
      requests:
        cpu: "0.5"
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
