apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: two
  name: two
spec:
  containers:
  - image: busybox
    name: first
    command: [bin/sh , -c, "echo hello; sleep 3600;"] 
    resources: {}
  - image: busybox
    name: second
    command: [bin/sh , -c, "echo hello; sleep 3600;"] 
