apiVersion: v1
kind: Pod
metadata:
 name: app
spec:
 containers:
 - name: app
   image: alpine:3.9.2
   command: ["/bin/sh", "-c"]
   args:
   - mkdir /metrics;
     while true; do
      date > /metrics/raw.txt;
      top -n 1 -b >> /metrics/raw.txt;
      sleep 5;
     done
   volumeMounts:
    - name: metrics
      mountPath: /metrics
 - name: adapter
   image: httpd:2.4.38-alpine
   command: ["/bin/sh", "-c"]
   args:
   - while true; do
      date=$(head -1 /metrics/raw.txt);
      memory=$(head -2 /metrics/raw.txt | tail -1 | grep -o -E '\d+\w' | head -1);
      echo "{\"date\":\"$date\",\"memory\":\"$memory\"}" > /metrics/adapted.json;
      sleep 5;
     done
   volumeMounts:
   - name: metrics
     mountPath: /metrics
 volumes:
 - name: metrics
   emptydir:
    
   
