apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: busybox
        name: nginx
        command: ["/bin/sh" , "-c", "echo hello; wget -o- www.google.com; sleep 600;"]
        resources: {}
status: {}
