apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: app-tier
 labels:
  app: multi-pods
  tier: service
spec:
 maxReplicas: 4
 minReplicas: 1
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: app-tier
 targetCPUUtilizationPercentage: 30

