apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  containers:
  - args:
    - bin/sh
    - -c
    - i=o;while true; do echo "$i:$(date)";$((i+1));sleep 1;done
    image: busybox
    name: busy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
