apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-liveness-pod
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
    ports:
    - containerPort: 80
    readinessProbe:
     httpGet:
      path: /
      port: 80
    livenessProbe:
     exec:
      command: 
      - ls
     initialDelaySeconds: 5
     periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Never
