apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server
  name: webserver
spec:
  containers:
  - image: nginx
    name: server
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
