apiVersion: batch/v1
kind: Job
metadata:
  name: box
  labels:
   app: box-job
spec:
#  activeDeadlineSeconds: 30
  completions: 5
  template:
    metadata:
     labels:
      app: box-job
    spec:
      containers:
      - command:
        - bin/sh
        - -c
        - while true; do echo hello; sleep 30; echo world; done
        image: busybox
        name: box
        resources: {}
      restartPolicy: Never
status: {}
