apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cronbox
spec:
  startingDeadlineSeconds: 17
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cronbox
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: cronbox
            command: [bin/sh, -c, "echo hello from sunil; sleep 5; echo bye;"] 
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
