apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: example-pvc
spec:
 accessModes:
 - ReadWriteOnce
 volumeMode: Filesystem
 resources:
  requests:
   storage: 256Mi
 storageClassName: local-storage-su
 
