apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pvc-pod
  name: pv-pod
spec:
  volumes:
  - name: pvc-data
    persistentVolumeClaim:
     claimName: example-pvc
  containers:
  - image: nginx
    name: pv-pod
    ports:
    - containerPort: 80
    resources: {}
    command: ["/bin/sh", "-c", "while true; do echo hello-to-pvc >> /var/www/html/pvcdata.txt; sleep 30; done;"]
    volumeMounts:
    - name: pvc-data
      mountPath: /var/www/html
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
