apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  hostPath:
   path: /tmp/wordpress 
