apiVersion: v1
kind: Pod
metadata:
 name: pod-pvc
spec:
 volumes:
 - name: data
   persistentVolumeClaim:
    claimName: pvc-data
 containers:
 - image: mongo:4.0.6
   name: mongo-db
   ports:
   - containerPort: 27017
     protocol: TCP
   volumeMounts:
   - mountPath: /data/db
     name: data
    
