apiVersion: v1
kind: Pod
metadata:
 name: secretinfo-pod
spec:
 containers:
 - name: secretnfopod
   image: busybox:1.30.1
   args:
   - sleep
   - "2600"
   env:
   - name: PASSWORD
     valueFrom:
      secretKeyRef:
       name: secretinfo
       key: password
