apiVersion: v1
kind: Service
metadata:
  name: data-tier-probe-demo
  labels:
    app: probe-demo
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis
  selector:
    tier: data
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-tier-probe-demo
  labels:
    app:  probe-demo
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: data
  template:
    metadata:
      labels:
        app:  probe-demo
        tier: data
    spec: # pod spec
      containers:
      - name: redis
        image:  redis:latest
        imagePullPolicy:  IfNotPresent
        ports:
        - containerPort:  6379
          name: redis
        livenessProbe:
          tcpSocket:
            port: redis # named port
          initialDelaySeconds:  15
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds:  5

