apiVersion: v1
kind: Pod
metadata:
  labels:
   app: v1
  name: nginx1
spec:
  containers:
  - image: nginx
    name: nginx1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
   app: v1
  name: nginx22
spec:
  containers:
  - image: nginx
    name: nginx1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
   app: v1
  name: nginx3
spec:
  containers:
  - image: nginx
    name: nginx1

