apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multi-pods
  name: multi-pods
spec:
 containers:
 - image: nginx
   name: nginx
   ports:
   - containerPort: 80
 - name: side-car
   image: curlimages/curl
   command: ["/bin/sh"]
   args: ["-c", "echo hello from sidecar; sleep 3000"]
