apiVersion: v1
kind: Pod
metadata: 
 name: readiness-http
 labels:
  test: readiness
spec:
 containers:
 - name: readiness-probe
   image: httpd:2.4.38-alpine
   ports:
   - containerPort: 80
   command: ["/bin/sh", "-c"]
   args: ["sleep 30 && httpd-foreground"]
   readinessProbe:
    httpGet:
     path: /
     port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
