apiVersion: v1
kind: Pod
metadata: 
 name: liveness-probe
 labels:
  test: liveness
spec:
 containers:
 - name: liveness-probe
   image: busybox:1.30.1
   ports:
   - containerPort: 8888
   command: ["/bin/sh", "-c"]
   args: ["timeout 30 nc -p 8888 -lke echo hi  && sleep 600"]
   livenessProbe:
    tcpSocket:
     port: 8888
    initialDelaySeconds: 3
    periodSeconds: 3
