apiVersion: v1
kind: Pod
metadata:
  labels:
    test: security-context
  name: security-context
spec:
  securityContext:
   runAsNonRoot: true
   runAsUser: 1000
   runAsGroup: 1000
  containers:
  - name: security-context
    image: busybox:1.30.1
    args:
    - sleep
    - "3600"
    securityContext:
     runAsUser: 2000
     readOnlyRootFilesystem: true
     

    
