apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - image: redis:latest
    name: redis
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
  - image: lrakai/microservices:server-v1
    name: server
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    env:
    - name: REDIS_URL
      value: redis://localhost:6379
  - image: lrakai/microservices:counter-v1
    name: counter
    env:
    - name: API_URL
      value: http://localhost:8080
  - image: lrakai/microservices:poller-v1
    name: poller
    imagePullPolicy: IfNotPresent
    env:
    - name: API_URL
      value: http://localhost:8080

