apiVersion: v1
kind: Pod
metadata:
  name: newpod
  labels:
    app: webapp
spec:
  containers:
  - name: newnginx
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi" #
        cpu: "500m" # 500m = 500mili cpus(1/2 cpu)
    ports:
    - containerPort: 80