apiVersion: v1
kind: Pod
metadata:
  name: redispod
  labels:
    app:  dblayer
spec:
  containers:
  - name: dbredis
    image:  redis:latest
    imagePullPolicy:  IfNotPresent
    ports:
    - containerPort:  6379