apiVersion: v1
kind: Pod
metadata:
  name: support-tier
  labels:
    app:  microservices
    tier: support
spec:
  containers:
    - name: counter
      image:  lrakai/microservices:counter-v1
      env:
        - name: API_URL
         # DNS for service discovery
          # Naming pattern:
          #   IP address: <service_name>.<service_namespace>
          #   Port: needs to be extracted from SRV DNS record
          value:  http://app-tier.k8-training:8080

    - name: poller
      image:  lrakai/microservices:poller-v1
      env:  
        - name: API_URL
          value:  http://app-tier.k8-training:8080
          #value:  http://app-tier.k8-training:$(APP_TIER_SERVICE_PORT_SERVER) 