apiVersion: v1
kind: Service
metadata:
  name: data-tier-service
  labels:
    app: microservice
    tier: data
spec:
  ports:
    - port: 6379
      protocol: TCP #default
      name: redis # optional when only 1 port
  selector:
    tier: data
  type: ClusterIP # default