apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-service
  name: nginx-svc
spec:
  ports:
  - name: "app"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
  type: LoadBalancer
