apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-tier
  labels:
    app:  microservice
    tier: support
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: support
  template:
    metadata:
      labels:
        app:  microservices
        tier: support
    spec:
      containers:
      - name: counter
        image:  lrakai/microservices:counter-v1
        resources:
          requests:
            cpu:  5m # 5 milli-cpu 

        env:
        - name: API_URL
          value:  http://app-tier.deployment:8080
      - name: poller
        image:  lrakai/microservices:poller-v1
        resources:
          requests:
            cpu:  2m
        env:
        - name: API_URL
          value:  http://app-tier:$(APP_TIER_SERVICE_PORT)