apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app:  microservices
spec:
  ports:
  - port:   6379
    protocol: TCP #default
    name: redis
  selector:
    tier: data # this matches with deployment metadata labels
  type: ClusterIP # default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-tier
  labels:
    app:  microservices
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: data
  template:
    metadata:
      labels:
        app:  microservices
        tier: data
    spec: # pod spec
      containers:
      - name: redis
        image:  redis:latest
        imagePullPolicy:  IfNotPresent
        ports:
        - containerPorts: 6379