apiVersion: batch/v1
kind: Job
metadata:
  name: box
  labels:
   run: busybox
spec:
  parallelism: 5
  template:
    metadata:
     labels:
      run: busybox
    spec:
      containers:
      - command:
        - bin/sh
        - -c
        - echo hello; sleep 30;echo bye
        image: busybox
        name: box
      restartPolicy: Never
