apiVersion: batch/v1
kind: Job
metadata:
  name: box
  labels:
   run: busybox
spec:
  completions: 5
  template:
    metadata:
     labels:
      run: busybox
    spec:
      containers:
      - command:
        - bin/sh
        - -c
        - echo hello;sleep 10; echo wo
        image: busybox
        name: box
      restartPolicy: Never
