apiVersion: v1
kind: Service
metadata:
 labels:
  app: count
  tier: datalayer
 name: backend
spec:
 ports:
 - name: redis
   port: 6379
   protocol: TCP
 selector:
  app: backend
 type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: count
    tier: datalayer
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
        readinessProbe:
         exec:
          command:
          - redis-cli
          - ping
         initialDelaySeconds: 5
        livenessProbe: 
         tcpSocket:
          port: redis
         initialDelaySeconds: 15 
        resources:
         requests:
          cpu: "50m"
          memory: "256Mi"
         limits:
          cpu: "50m"
          memory: "256Mi"
          
