apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: server-hpa
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
  apiVersion: v1
  kind: Deployment
  name: server
 targetCPUUtilizationPercentage: 60
