apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pvc-busybox
  name: busybox
spec:
  volumes:
  - name: myvolume
    persistentVolumeClaim:
     claimName: mypvc
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    volumeMounts:
    - name: myvolume
      mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
