apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
   app: 2pods
  name: busybox
spec:
  restartPolicy: Never
  volumes:
  - name: myvolume
    emptyDir: {}
  containers:
  - image: busybox
    name: 1pod
    imagePullPolicy: IfNotPresent
    args:
     - /bin/sh
     - -c
     - sleep 3600
     - wget -O- localhost:8081
    volumeMounts:
    - name: myvolume
      mountPath: /etc/foo
  - image: busybox
    name: 2pod
    ports:
    - containerPort: 8081
    imagePullPolicy: IfNotPresent
    args:
     - /bin/sh
     - -c
     - sleep 3600
    volumeMounts:
    - name: myvolume
      mountPath: /etc/foo
